[package]
name = "uol-layout"
version = "1.0"
entrypoint = "lib/lib.typ"
authors = ["Maximilian Dannemann"]
license = "MIT"
description = "A clean template for academic writing at University of Oldenburg."
repository = "https://github.com/maxdannemann/uol-typst-template"
keywords = ["academic", "thesis", "report", "research", "hochschule-emden-leer"]
categories = ["report", "thesis"]
compiler = "0.13.1"
disciplines = ["computer-science", "engineering", "business", "economics"]

[template]
path = "example"
entrypoint = "main.typ"
thumbnail = "example/snapshots/thumbnail.png"
